version: '3'
services:
  web:
    build:
      context: cruzverdeapi
      dockerfile: Dockerfile
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    environment:
      POSTGRES_PORT_5432_TCP_ADDR: ec2-184-73-197-211.compute-1.amazonaws.com
      POSTGRES_DATABASE: d14cab64gsgbvg
      POSTGRES_USERNAME: yfwimwyujwurte
      POSTGRES_PASSWORD: 1bd7021795c86d6ee850170c415c2ced516a10a3aeafb51a712efdd1c60e3210
    volumes:
      - ./cruzverdeapi:/cruzverdeapi
    ports:
      - "3000:3000"